version: '3.8'

services:
  # خدمة قاعدة البيانات PostgreSQL
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=blog_db
      - POSTGRES_USER=blog_user
      - POSTGRES_PASSWORD=blog_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  # خدمة تطبيق Django
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    environment:
      - DB_NAME=blog_db
      - DB_USER=blog_user
      - DB_PASS=blog_password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data:
